name: Lint (Examine Error)

on:
  push:
  pull_request:
    branches: [ "main" ]
    
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v2
        
        - uses: game-ci/unity-builder@v2
          env:
            UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
            UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
            UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
          with:
            targetPlatform: Android
            projectPath: test-project
            
        - uses: actions/upload-artifact@v2
          with:
            name: Build
            path: buld
