name: Backend Lint

on:
  push:
  pull_request:
    branches: [master]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: executing remote ssh commands using key
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          #password: ${{ secrets.PASSWORD }}
          key: ${{ secrets.KEY }}
          port: 22
          script: |
            cd Github-Action-test && git pull
            npm install --no-save
            pm2 delete backend
            pm2 start test.js --name "backend"
